--require("ibl").setup {
--    scope =    {
--       enabled = false,
--       show_start = false,
--       show_end = false,
--       injected_languages = false,
--       highlight = { "Function", "Label" },
--       priority = 500,
--   }
--}
